/**
 * Overlay (patch-list) generation.
 *
 * The overlay format is verified against the shipped DSH files, not guessed:
 * a top-level YAML **array** of patch entries. The insert form is taken from
 * `packages/experimental/inspector/cordis.patch.yml`:
 *
 * ```yaml
 * - insert:
 *     - id: experimental-inspector
 *       name: './lib/index.js'
 * ```
 *
 * A relative `name` is anchored to the overlay file's own directory, which is
 * how a locally developed plugin is mounted without installing it into the
 * profile. This module always emits absolute paths instead, precisely so the
 * anchor does not matter and the overlay stays correct wherever it is written.
 *
 * Emitted YAML is produced by hand rather than by a dependency: the shapes are
 * small, fixed, and fully controlled here, and the DevKit has no YAML parser to
 * rely on outside the DSH checkout.
 */

import { assertEntryFile } from './entry.mjs'

/** The id used for the debugger row. Matches the plugin's exported `name`. */
export const DEBUGGER_ID = 'dsh-debugger'

/** The id used for the plugin under test unless one is derived. */
export const DEFAULT_PLUGIN_ID = 'plugin-under-test'

/**
 * Build the overlay document as structured rows.
 *
 * Keeping this as data (rather than a string) is what lets tests assert the
 * *shape* — that the entry is a file, that both rows exist — separately from
 * formatting.
 *
 * Entries are validated with `assertEntryFile`, which is the guarantee that a
 * directory can never reach the emitted `name`. The filesystem probe is
 * injectable so the generator can be tested without creating real files; the
 * extension check (the part that actually blocks a directory) never depends on
 * the disk.
 *
 * @param {{
 *   pluginEntry?: string|null, pluginId?: string|null,
 *   debuggerEntry?: string|null, includeDebugger?: boolean,
 *   pluginConfig?: object|null,
 *   exists?: (path: string) => boolean
 * }} options
 * @returns {object[]} patch rows
 */
export function buildOverlayRows(options = {}) {
  const rows = []
  const insert = []
  const checkDeps = options.exists ? { exists: options.exists } : {}

  // The plugin under test is inserted first so it appears above the observer in
  // the tree; either order loads, but debugging reads better with the subject
  // first.
  if (options.pluginEntry) {
    const entry = assertEntryFile(options.pluginEntry, checkDeps)
    const row = { id: options.pluginId || DEFAULT_PLUGIN_ID, name: entry }
    if (options.pluginConfig) row.config = options.pluginConfig
    insert.push(row)
  }

  if (options.includeDebugger !== false && options.debuggerEntry) {
    const entry = assertEntryFile(options.debuggerEntry, checkDeps)

    // The plugin-under-test row and the kernel row must never share an id:
    // cordis refuses the entire tree with "duplicate loader entry id: X"
    // (loader/config/group.ts:64) rather than loading one of them.
    //
    // Two ways that happens, and both were only found by running a real boot:
    //
    //   1. `--plugin` points at the kernel itself, so the same *file* is
    //      inserted twice.
    //   2. `--plugin` points at some other file that merely *derives* the id
    //      `dsh-debugger` (e.g. `D:\mods\dsh-debugger\index.mjs` names the
    //      directory, not the kernel), so the kernel row collides by *id*.
    //
    // Case 1 is folded away, because the subject row already mounts that exact
    // file and the extra row is genuinely redundant. Case 2 keeps both rows —
    // the subject is a different plugin the author asked to debug — and
    // disambiguates the kernel's id instead.
    const subject = insert[insert.length - 1]
    const subjectEntry = subject ? subject.name : null
    const collides = Boolean(subject) && (subjectEntry === entry || subject.id === DEBUGGER_ID)

    if (collides && subjectEntry === entry) {
      // Same file: one row, still announced.
      subject.config = { announce: true, ...(subject.config ?? {}) }
    } else {
      insert.push({
        // A distinct id keeps the kernel mountable alongside a subject that
        // already claimed `dsh-debugger`.
        id: collides ? `${DEBUGGER_ID}-kernel` : DEBUGGER_ID,
        name: entry,
        // `announce` prints the one-line readiness banner the debug-boot output
        // promises, so a user can tell the kernel mounted without opening /debug.
        config: { announce: true },
      })
    }
  }

  if (insert.length) rows.push({ insert })
  return rows
}

/**
 * Serialize overlay rows to YAML.
 *
 * @param {object[]} rows
 * @returns {string}
 */
export function renderOverlay(rows) {
  const lines = [
    '# Generated by dsh-debug-boot. Regenerated on every run; edit the generator,',
    '# not this file.',
    '#',
    '# Entries are absolute file paths on purpose: a relative name is anchored to',
    "# this overlay's own directory, and Node's ESM import() cannot directory-import.",
    '',
  ]

  for (const row of rows) {
    if (row.insert) {
      lines.push('- insert:')
      for (const entry of row.insert) {
        lines.push(`    - id: ${yamlScalar(entry.id)}`)
        lines.push(`      name: ${yamlScalar(entry.name)}`)
        if (entry.config) {
          lines.push('      config:')
          for (const [key, value] of Object.entries(entry.config)) {
            lines.push(`        ${key}: ${yamlScalar(value)}`)
          }
        }
      }
    }
  }

  return `${lines.join('\n')}\n`
}

/**
 * Render a YAML scalar, quoting when the value could be misread.
 *
 * Windows paths contain `:` and `\`, both of which are unsafe unquoted in YAML;
 * always quoting a string is the simple correct choice here.
 *
 * @param {unknown} value
 * @returns {string}
 */
export function yamlScalar(value) {
  if (typeof value === 'boolean' || typeof value === 'number') return String(value)
  return `'${String(value).replace(/'/g, "''")}'`
}

/**
 * Derive a readable plugin id from an entry path.
 *
 * The id appears in the profile tree and in `/debug plugins`, so it should name
 * the plugin rather than a generic placeholder whenever something better than a
 * filename is available.
 *
 * @param {string} entry absolute entry file path
 * @returns {string}
 */
export function derivePluginId(entry) {
  const base = String(entry).replace(/[\\/]+$/, '').split(/[\\/]/).pop() ?? ''
  const withoutExt = base.replace(/\.(mjs|cjs|js|ts)$/, '')
  // `index`/`main` name the file, not the plugin; fall back to the directory.
  if (withoutExt && !['index', 'main'].includes(withoutExt)) return sanitizeId(withoutExt)

  const parts = String(entry).replace(/[\\/]+$/, '').split(/[\\/]/)
  const dir = parts[parts.length - 2]
  return dir ? sanitizeId(dir) : DEFAULT_PLUGIN_ID
}

/**
 * Coerce a name into a loader-safe id.
 *
 * @param {string} value
 * @returns {string}
 */
export function sanitizeId(value) {
  const cleaned = String(value).trim().toLowerCase().replace(/[^a-z0-9._-]+/g, '-').replace(/^-+|-+$/g, '')
  return cleaned || DEFAULT_PLUGIN_ID
}
